version: '2'
services:

  php:
    build:
      dockerfile: Dockerfile-fpm
      context: 'php-7.1'
    image: ${STACK_PHP_IMAGE}
    environment:
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
      - PHP_ENABLE_XDEBUG=${PHP_ENABLE_XDEBUG}
    volumes:
      - ./test:/test
  php-nginx:
    build:
      dockerfile: Dockerfile-fpm-nginx
      context: 'nginx'
    image: ${STACK_PHP_IMAGE}-nginx
    environment:
      - PHP_ENABLE_XDEBUG=${PHP_ENABLE_XDEBUG}

  php-alpine:
    build:
      dockerfile: Dockerfile-fpm-alpine
      context: 'php-7.1'
    image: ${STACK_PHP_IMAGE}-alpine
    volumes:
      - ./test:/test
  php-alpine-nginx:
    build:
      dockerfile: Dockerfile-fpm-alpine-nginx
      context: 'nginx'
    image: ${STACK_PHP_IMAGE}-alpine-nginx

  php-alpine-nginx-xdebug:
    build:
      dockerfile: Dockerfile-fpm-alpine-nginx-xdebug
      context: 'nginx'
    image: ${STACK_PHP_IMAGE}-alpine-nginx-xdebug
